version: '3.3'
services:
  backend:
    build:
      context: ./backend
      args:
        env: dev
    command: /start-reload.sh
    environment:
      - 'JUPYTER=jupyter notebook --ip=0.0.0.0 --allow-root'
      - SERVER_NAME=${DOMAIN}
      - SERVER_HOST=http://${DOMAIN}
    networks:
      default:
        aliases:
          - ${DOMAIN}
    ports:
      - '8888:8888'
    volumes:
      - ./backend/app:/app
  backend-tests:
    build:
      context: ./backend
      dockerfile: tests.dockerfile
      args:
        env: dev
    environment:
      - JUPYTER=jupyter notebook --ip=0.0.0.0 --allow-root
    volumes:
      - ./backend/app:/app
  frontend:
    build:
      context: ./frontend
    environment:
      - SERVER_HOST=http://${DOMAIN}
    ports:
      - '5555:5555'
  proxy:
    ports:
      - '80:80'
    volumes:
      - './nginx.template:/etc/nginx/conf.d/default.conf:ro'
