version: '3.3'
services:
  backend:
    environment:
      - SERVER_NAME=${DOMAIN}
      - SERVER_HOST=https://${DOMAIN}
  frontend:
    environment:
      - SERVER_HOST=https://${DOMAIN}
  db:
    volumes:
      - app-db-data:/var/lib/postgresql/data/pgdata
  proxy:
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - './nginx.template:/etc/nginx/conf.d/default.conf:ro'
      - '/etc/letsencrypt:/etc/letsencrypt:ro'
      - '/var/www/letsencrypt:/var/www/letsencrypt:ro'
    restart: always

volumes:
  app-db-data: